# Project Name(s): English Contextual Baseline Database
# Program Name: yelp_3D_frequencies.py
# Date: 03/11/2023
# Description: Reads in the reviews.json file containing a large subset of the Yelp Review data dump and generates visual information explaining details regarding the dataset

# ================================================================================
# Included libraries
# Pandas: storing data
# ================================================================================

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from textblob import TextBlob
import pandas as pd
import collections
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def remove_punc(input_string):
    # Punctuation string
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    
    cleaned_string = ""

    # If the character is not punctuation append it
    for char in input_string:
        if char not in punc:
            cleaned_string += char

    return cleaned_string

if __name__ == "__main__":    
    # Load csv file, minimize memory usage using chunks
    yelp_review_chunks = pd.read_csv("reviews.csv", chunksize=10000) 

    # Five lists to hold the reviews based on the number of stars
    review_stars = [ [], [], [], [], [] ]

    # 2D list to hold the most common words found in each review
    review_words = [ [], [], [], [], [] ]

    # Stop words
    # List generated by ChatGPT
    stopwords.words("english")

    stop_words = set(stopwords.words("english"))
    stop_words.update(['the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me', 'i', 'me', 'my', 'mine', 'we', 'us', 'our', 'ours', 'he', 'him', 'his', 'she', 'her', 'hers', 'it', 'its', 'they', 'them', 'their', 'theirs', 'ive', 'im', 'also'])

    # Iterate through the chunks
    for yelp_review_chunk in yelp_review_chunks:

        # Extract the review text based on the number of stars
        for index, row in yelp_review_chunk.iterrows():
            if (row["stars"] == 5.0):
                review_stars[4].append(row["text"])
            elif (row["stars"] == 4.0):
                review_stars[3].append(row["text"])
            elif (row["stars"] == 3.0):
                review_stars[2].append(row["text"])
            elif (row["stars"] == 2.0):
                review_stars[1].append(row["text"])
            else:
                review_stars[0].append(row["text"])
        
    # List the hold the frequency of each word
    word_freq = [ [], [], [], [], [] ] 

    for i in range(len(review_stars)): 
        # Count the occurence of each word
        num_words = collections.Counter(word.lower() for word in remove_punc(" ".join(review_stars[i])).split() if word.lower() not in stop_words)
        most_common = num_words.most_common(25)
        
        for word, freq in most_common:
            review_words[i].append(word)
            word_freq[i].append(freq)
	
    # List the hold the emotional value of each word
    word_sent = [ [], [], [], [], [] ]
    
    # For each review type iterate through all words
    for i in range(len(review_words)):
        for word in review_words[i]:
            blob = TextBlob(word)
            word_sent[i].append(float(blob.sentiment.polarity))

    # Hold the color values of each of the word sentiment values
    sentiment_color_grades = [ [], [], [], [], [] ]
    
    # For each review type iterate through all words
    for i in range(len(word_sent)):
        for sentiment in word_sent[i]:
            # Negative sentiment corresponds to red
            if sentiment < 0:  
                sentiment_color_grades[i].append("r")
            # Positive sentiment corresponds to green
            elif sentiment > 0:
                sentiment_color_grades[i].append("g")
            # 0 corresponds to blue
            else:
                sentiment_color_grades[i].append("b")
 
    figure = plt.figure(figsize=(10, 8))
    ax = figure.add_subplot(111, projection="3d")
    for i in range(len(review_words)):
        # Only plot words with a non-zero sentiment value
        if word_sent[i] > 0.1 or word_sent[i] < -0.1: 
            ax.scatter(word_freq[i], word_sent[i], i+1, c=sentiment_color_grades[0])
            for j in range(len(review_words[i])):
                ax.text(word_freq[i][j], word_sent[i][j], i+1, review_words[i][j], color="black")

    ax.set_xlabel("Frequency")
    ax.set_ylabel("Sentiment")
    ax.set_zlabel("Stars")
    
    plt.show()
    print("Script done...")
