# this file contains all of the keywords

tech = ['cybersecurity', 'internet','communication','application','technical',
'robotics','wheel','automation','energy','applied','devices','tools','capabilities',
'wireless','wi-fi','scientific','equipment','machinery','knowledge','software','hardware',
'storage','tech','gadget','business', 'technology', 'watch', 'mobile', 'phone', 'computer',
'electronics', 'technological', 'code', 'Python', 'Java', 'C', 'infomration', 'applications',
'game', 'storage', 'virtual', 'industry', 'robots', 'process', 'machinery', 'business',
'media', 'system', 'digital', 'cyber', 'media', 'intelligence', 'labs']
hist = ['historic','history','age','story','etymology','chronical','period','era',
'biography','arts','iconology','trace','geology','milestone','background','record','ancient',
'story', 'chronicle', 'past', 'record', 'geography', 'art', 'prehistory', 'heritage',
'biography', 'life', 'experience', 'century', 'social', 'origins', 'studies', 'meaning',
'philosophy', 'historical', 'legacy', 'academic', 'future', 'world', 'country', 'civics',
'backstory', 'time', 'military', 'theory', 'facts', 'historian', 'timeline', 'knowledge',
'timeline', 'origin', 'geneaology', 'activity', 'issues', 'language', 'decade', 'reality']
advertisement = ['buy','sell','cheap','product','new','easy','simple','promotion',
'pre-order','order','shipping','free','marketing','love','should', 'promotion', 'publicity',
'ad', 'mailer', 'billboard','poster', 'propoganda', 'transaction', 'advertise', 'flyer', 
'magazine', 'editorial', 'commercial', 'sponsor', 'trailer', 'cartoon', 'informercial', 'photograph',
'facebook', 'twitter', 'meta', 'instagram', 'campaign', 'adverts', 'promos', 'sign', 'announcement',
'merch', 'store', 'selling', 'video', 'airing', 'disclaimer', 'tabloid', 'description', 
'page', 'post', 'scam', 'airing', 'selling','tv', 'press', 'ticket', 'content', 'social']
religion = ['religion','religious','pagan','islam','faith','christianity','church',
'bible','muslim','convert','spiritual','doctrine','judaism','secular','evangelical','devout',
'heathen','bigot','preach','tolerance','divinity','unbeliever', 'paganism', 'worship', 'religious',
'orthodox', 'meditation', 'church', 'conformist', 'muslim', 'catholicism', 'deity',
'belief', 'morality', 'gods', 'ethnic', 'law', 'politics', 'symbol', 'tradition', 'spiritual', 'denomination',
'protestant', 'supersistion', 'speech', 'moral', 'lifestyle', 'book', 'myth', 'state', 'worldview',
'personal', 'scriptures', 'region', 'background', 'jesus', 'path', 'non', 'nationalism']
political = ['administration','affairs','associative','government','power','election',
'elect','money','vote','bill','law','yea','nay','polls','money','public' ,'office','representation',
'state','sociopolitical','law','geopolitics','local','federal', 'policies', 'aristotle', 'law', 'economic',
'socio', 'presidency', 'local', 'election', 'partisan', 'governance', 'debate', 'parliament',
'democratic', 'republican', 'socialist', 'populist', 'capitalist', 'incumbency', 'monarchy', 'mudslinging',
'liberal', 'dukes', 'corruption', 'media', 'military', 'officeholders', 'midterm', 'rightwing', 'leftwing', 
'gop', 'business', 'anarchism', 'electoral', 'reformers', 'controversial', 'factional']
scientific = ['discovery','biology','chemistry','astronomy','discovery','finding',
'data','sources','climate','element','energy','etemology','botany','control','evolution',
'experiment','fossil','fact','hypothesis','immunology','lab','measure','microbiology','mineral',
'molecule','motion','observe','physical','research','science','theory','weather', 'neuroscience', 
'research', 'geology', 'physics', 'humanities', 'theory', 'math', 'meterology', 'linguistics', 
'facts', 'systematics', 'culture', 'news', 'study', 'empirical', 'bioscience', 'analysis', 'field of study',
'arts', 'physics', 'robotics', 'molecular', 'studies', 'doctors', 'math', 'STEM', 'futuristic', 'coding']
cultural = ['culture','accomplishment','civilization','cultivation','lifestyle',
'society','race','tradition','country','heritage','dress','crops','societies','courtesy',
'belief','ethics','delicacy','advancement','civility','discrmination', 'historial', 'racial', 'architectural',
'religion', 'literacy', 'marxism', 'spiritual', 'ecological', 'popular culture', 'intellectual', 'music',
'ecological', 'writing', 'traditional', 'ideology', 'writing', 'language', 'science', 'ritual',
'cultural studies', 'contemporary', 'symbol', 'national', 'clothing', 'generational', 'personal', 
'theological', 'personal', 'social mores', 'familial', 'race', 'geographic', 'popular', 'museums']
nature = ['nature','trees','plants','animals','chemical','biological','reproduction',
'weather','climate','coast','ocean','beach','desert','earth','planet','universe','life',
'environmemt','nurture','wilderness','evolution','sun','stars', 'existence', 'universe', 'nurture', 
'ocean', 'disposition', 'glacier', 'atmosphere', 'trait', 'human', 'wildlife', 'sea', 'water vapor', 
'inherent', 'beauty', 'plants', 'sea', 'precipitation', 'flora', 'pond', 'quality', 'variety', 'forest',
'paradoxes', 'eco', 'evolution', 'fish', 'monkey', 'reality', 'character', 'wild', 'water', 'hemisphere',
'genetics', 'origin', 'city', 'solar system', 'unique', 'intrinsic', 'civilization', 'climate']
economy = ['money','stocks','bonds','rates','morgage','crash','DOW','S&P','fed','hikes',
'strong','weak','buying','selling','capitalism','sector','savings','economy','budget',
'capital','cash','bankrupt','competition','consumer','cut', 'society', 'financial', 'country', 
'recession', 'economist', 'trade', 'slowdown', 'downturn', 'barter', 'exports', 'crisis', 'consumption',
'goods', 'stock', 'population', 'jobs', 'military', 'distribution', 'market', 'slump', 'jobless rates', 
'inflation', 'nominal gdp', 'managment', 'macro', 'micro', 'political', 'trading', 'service', 
'subprime mortgage crisis', 'covid', 'supply', 'community', 'pandemic', 'slowing', 'commodity price']
government = ['policy','governmental','congress','house','senate','security','military',
'weapons','debt','national','nation','united','president','vice','representative','council',
'economy','impeach','elect','vote','campaign','money','fundraise','gerrymander', 'regime', 'legislature', 
'judiciary', 'bureaucracy', 'policy', 'executive', 'governmental activity', 'parliament', 'ministry',
'civil', 'polity', 'people', 'soverignty', 'local', 'policies', 'corporations', 'lawmakers', 'contractor', 
'territory', 'person', 'election', 'capitalism', 'anti', 'oligarchy', 'empire', 'council', 'legislative', 
'protest march', 'army', 'companies', 'city', 'sector', 'school', 'central', 'pharma', 'taxes']
sports = ['football', 'touchdown', 'score', 'extra point', 'soccer', 'goal', 'offsides', 'kick',
'home', 'run', 'bases', 'bat', 'ball', 'puck', 'hockey', 'baseball', 'skates', 'rink', 'game', 'overtime',
'NFL', 'points', 'bowling', 'volleyball', 'spike', 'activities', 'competition', 'game', 'skiing', 'polo', 
'physical', 'music', 'rowing', 'wrestling', 'action', 'work', 'call', 'concert', 'spar', 'party', 
'kill', 'athlete', 'martial', 'performance', 'gaming', 'golf', 'badminton', 'wipeout', 'activity', 
'team sport', 'television', 'working', 'cheerlead', 'upfield', 'gyms', 'skateboard', 'celebrity', 'casino', 
'cars', 'event', 'figure skating', 'leisure', 'hiking', 'politics', 'resort', 'competitions', 'compressions', 'mma'] 